title: Homepage for karljian
page-top-title: Homepage for K.J
top-section-bg-text: Geophysical Geodesy
home-subtitle: GuangyuJian | Karljian | 简光煜
copyright-text: '&copy; Guangyu Jian 2025-now. All Rights Reserved.'
